version: '3'
services:
  backupdb:
    restart: always
    volumes:
      - backup-data:/backup
    environment:
      COCKROACH_HOST: roach1
      COCKROACH_PORT: 26257
      COCKROACH_USER: root
      COCKROACH_DB: db
      CRON_TIME: "0 0 * * *"
      INIT_BACKUP: "true"
      MAX_BACKUPS: 3
    build: .
    networks:
      - roachnet

volumes:
  backup-data:
  db-data:

networks:
  roachnet:
    driver: bridge